apiVersion: apps/v0
kind: Deployment
metadata:
  name: simple-node
  labels:
    app: simple-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
      - name: simple-node
        image: elsrickle/simple-node
        ports:
        - containerPort: 80